### ISSUE TITLE
弱弱地建议加链接

### ISSUE THREAD

**Issue by 29Esther** [Inter-U/prototype#10]
额。。。。

>IU02
> * 用户可以查看自己发过的问题

所以
> 102个问题 | 32个回答

问题和回答要加链接吧。。那个王大狗也要加链接吧~~

另外，你都有在卡片上写多少人看了，确定不写多少人被问到过吗？

**Comment by 29Esther** [comment]
哦。。是不是因为Sprint 1没有这个功能所以不用加？

**Comment by tjwudi** [comment]
嗯，写多少人被问到过更好。我会改。

你说的链接也是要加的。
