### ISSUE TITLE
建议每个问题每个用户只能回答一次。

### ISSUE THREAD

**Issue by 29Esther** [Inter-U/prototype#11]
![qq 20150324211448](https://cloud.githubusercontent.com/assets/5023687/6802408/216b8e66-d26b-11e4-91be-286df705652c.png)
你这个右下角的5个回复的意思是我已经回复了5条了？？

那么问题来了，一个问题每个用户能回答几次？
我觉得只有一次机会比较好。比如：

![qq 20150324211823](https://cloud.githubusercontent.com/assets/5023687/6802424/5540ccce-d26b-11e4-913a-8b02f077cd2a.png)

**Comment by 29Esther** [comment]
我觉得这样是为了防止别人刷楼。。

**Comment by 29Esther** [comment]
一直忘记 @tjwudi

**Comment by tjwudi** [comment]
我个人觉得没有必要吧，但是刷楼可能是个问题，在Sprint 1暂时不考虑。控制一下边界。

你说的我明白，防止聊起来还有第二种做法，就是StackOverflow那种，楼内评论。[点击这里看例子](http://stackoverflow.com/questions/29232667/looping-through-lists-better-method) 你觉得呢

**Comment by 29Esther** [comment]
嗯。question那页有写楼内回复。
因为有楼内回复，所以一个人不需要回答一个问题多次。

**Comment by tjwudi** [comment]
我并不是这个意思。我的意思是，楼内回复可以削减刷楼。你提前做了这个我觉得是很OK的。

我们就不考虑恶意刷楼的情况了，那样对于MVP来说太复杂了。实际上楼内回复在MVP1里面应该也是不会做的，我到时候会把富余出来的部分切到另外一个分支。

**Comment by 29Esther** [comment]
嗯。
