### ISSUE TITLE
注册的时候需要一个昵称

### ISSUE THREAD

**Issue by PanruifengWawa** [Inter-U/prototype#12]
你看首页已经问题展示的网页，有个王二狗，那么也就是说需要一个昵称

**Comment by 29Esther** [comment]
用户名啊。。

**Comment by tjwudi** [comment]
@29Esther 登出你的GitHub账户看一下首页

**Comment by 29Esther** [comment]
![qq 20150324220041](https://cloud.githubusercontent.com/assets/5023687/6803240/39fc9e56-d271-11e4-874d-fd129da59f25.png)
无敌三角组合啊。。。
对的啊~我觉得很正确啊。。

**Comment by tjwudi** [comment]
嗯。输错密码可以按照邮箱找回（后面再加这个需求，我先在TB上加上）

**Comment by tjwudi** [comment]
我close掉这个case，大家辛苦。

**Comment by 29Esther** [comment]
谢谢@PanruifengWawa
