### ISSUE TITLE
当新增一个问题的时候不需要重复输入公司名称

### ISSUE THREAD

**Issue by PanruifengWawa** [Inter-U/prototype#13]
个人建议把“选择你面试的公司”放到所有问题的左上方，不需要重复，也就是一次贡献，只贡献一个公司的面试问题，可以是不同职位的。

然后觉得把“选择你面试的公司”改成“填写你面试的公司” 比较好

**Comment by tjwudi** [comment]
valid，我稍后修改。

**Comment by 29Esther** [comment]
Agreed !

**Comment by tjwudi** [comment]
fixed
