### ISSUE TITLE
分页功能

### ISSUE THREAD

**Issue by tjwudi** [Inter-U/prototype#14]
卡片列表等列表都要分页

**Comment by 29Esther** [comment]
要分页吗？

**Comment by PanruifengWawa** [comment]
如果一个老用户有过很多问题了，那么当访问该网页的时候，全部加载出来就会很慢，很影响用户体验。
当然不分页也可以的吧，可以借鉴人人，底部放一个“查看更多”的按钮，一点才会出现接下来的10个（不一定10个）卡片，这两种原理是一样的，就看哪一种好做

**Comment by tjwudi** [comment]
@PanruifengWawa 嗯，异步加载其实也好做。这个还要考虑一下。
