### ISSUE TITLE
当新增问题很多的时候，有点不太友好

### ISSUE THREAD

**Issue by PanruifengWawa** [Inter-U/prototype#15]
当新增问题撑满整个网页的时候，也就是按钮“新增一个问题”在网页最底部的时候，再次按一下这个按钮，需要鼠标往下滚才能看见你的你新增的问题描述，这样有点不友好，希望在这种情况下，是自动往下翻，而不是需要人为的翻

**Comment by tjwudi** [comment]
+1，今晚前修复。
