### ISSUE TITLE
主页被改了？Perfer原来的设计

### ISSUE THREAD

**Issue by 29Esther** [Inter-U/prototype#16]
突然发现主页被改了。。
我怕觉得如果Tab在左边的话，不如fixed在左边，然后把信息卡放在全部问题上面。。

**Comment by tjwudi** [comment]
![screen shot 2015-03-25 at 10 43 14 pm](https://cloud.githubusercontent.com/assets/5257816/6827063/595660a0-d340-11e4-8fc3-ce9a0b95a24a.png)

我其实是按这个来的。你的Fixed是啥意思

**Comment by tjwudi** [comment]
Will be fixed soon.

**Comment by tjwudi** [comment]
侧边栏可能加上筛选功能？
