### ISSUE TITLE
输入框没有提交按钮

### ISSUE THREAD

**Issue by PanruifengWawa** [Inter-U/prototype#2]
在 http://development.inter-u.divshot.io/#/question 中
页面最后的“李桂花，”  后面有个输入框，那是干嘛的？如果是用户回答面试问题的输入框的话，那么提交按钮在哪里？@29esther

**Comment by PanruifengWawa** [comment]
强迫症表示，那个输入框没有和王二狗的回复对齐，跑到“支持，反对”那里了

**Comment by 29Esther** [comment]
提交按钮是我忘加了。。

至于布局，两个是有区别的， 和王二狗的回复对齐 的是评论王二狗的回复，最下面的是回答整个问题，和王二狗的回复并列的，明白吗？

**Comment by 29Esther** [comment]
已修正。
