### ISSUE TITLE
“评论 感谢 收藏 分享 没有帮助 举报”按钮过于密集了

### ISSUE THREAD

**Issue by PanruifengWawa** [Inter-U/prototype#3]
个人觉得这些太过于密集，是否可将没有帮助和举报两个按钮放到回复的右上角？然后将这些按钮的间距稍微分开点？（参考微博的）@29esther 
![6p 2 h6l24 4 yiev2w dh6](https://cloud.githubusercontent.com/assets/8222837/6783560/44c9fb88-d1b5-11e4-9671-72af69815db1.png)

**Comment by 29Esther** [comment]
不考虑美观，只看功能好嘛！
