### ISSUE TITLE
关于注册的问题

### ISSUE THREAD

**Issue by PanruifengWawa** [Inter-U/prototype#5]
注册那里，密码是否需要重复确认？
还有一个小问题就是，注册需要的信息是否少了一点？比如性别和年龄（或者还有其他的）？因为HR在招收职员的时候，还会考虑应试者年龄和性别（等等）。又或者暂时不考虑？以后需要的时候在完善？@29esther

**Comment by 29Esther** [comment]
暂时不考虑吧，年龄性别啥的。

我觉得重复确认密码没什么必要。。个人是这样觉得的。。。

**Comment by PanruifengWawa** [comment]
那么要在开发的过程中注意可扩展性，毕竟要做线上招聘的话，至少需要一些真实的个人情况（姓名等）@tjwudi

**Comment by WYShine** [comment]
重复确认密码+1, 感觉这样比较符合习惯。

**Comment by PanruifengWawa** [comment]
不是习惯，是怕你打字泰国，按错一个键，使得密码丢失

**Comment by 29Esther** [comment]
知乎注册就没有重复密码啊。。
很多快节奏的网站都不需要重复密码。。
处于用户交互考虑，我真的觉得重复密码不是很有必要。。要么，这一点我们保留一下吧。。

**Comment by Ada12** [comment]
建议重复密码，因为我就很容易打错

**Comment by WYShine** [comment]
1.知乎的注册好像是用邮箱吧？而且邮箱应该要验证。所以就算用户输错了密码，也可以通过邮箱找回。。我们的use case 里面说第一个版本暂时不对邮箱进行验证，所以一遍密码输错的话，找回是个麻烦的问题。
2.而且现在有三个人提出这个问题，也在一定程度上体现了用户需求，就我作为用户的体验来说，我不是很愿意担着输错密码的风险来节省输第二遍密码的那几秒钟

**Comment by 29Esther** [comment]
不是啊。我刚刚特地尝试了一下，不需要邮箱验证，输错了就是错了。

**Comment by WYShine** [comment]
呃可能表达有问题。。比如你本来想设置的密码是123456，但是手一抖输成了abcdef，注册成功系统直接登录了。。你下次再登陆的时候发现用123456的密码登录失败，而且你不知道你注册的时候手抖的幅度。。只输一遍密码的劣势就在这。。这个账号就gg了

**Comment by 29Esther** [comment]
对的。我明白你的意思。但是对于多数人来说这种情况都很少，尤其是熟练使用网络的人（我们的客户）。
可能你没有发现，但是事实上越来越多的网站，选择抛弃重复确认密码这一条，这完全是出于用户考虑的，这样可以让你的注册变得更简单，更方便。
![qq 20150324154913](https://cloud.githubusercontent.com/assets/5023687/6797475/5dcfaaa0-d23d-11e4-82e0-7c18b9ce4723.png)

我觉得这一点我们可以先保留一下。

**Comment by tjwudi** [comment]
我就提示一下…
1. 目前Use Case里面的内容是可以改的，并不是说肯定不做邮件验证。如果大家觉得OK，那就做。
2. 做了邮件其实还有更省事的办法，就是不需要用户输入密码，只输入邮箱。发给他一个初始密码，他登录后再让他改。
你们尽量通过讨论后达成一致。辛苦！：）

**Comment by PanruifengWawa** [comment]
按照目前的样子来说，邮箱验证是需要的
因为注册时填的信息太少，只要邮箱，。账号和密码、
在登录界面有忘记密码这个选项，那么请问我忘记了密码，只记得账号和密码，怎么找回？更有可能账号也忘记了

**Comment by 29Esther** [comment]
邮箱验证可有可无吧。
忘记了就重新注册吧。
那我注册了QQ忘记了账号怎么办？重新注册一个呗。。

**Comment by tjwudi** [comment]
见#12

**Comment by Ada12** [comment]
QQ注册不像是我们普通的注册一样，QQ注册之后是系统自动分配给我们一个QQ号码。而我们现在的注册是基于我们自己的邮箱的，所以邮箱名一般不会忘记，而且我觉得邮箱验证是必须的，确保信息的真实性，而且每个邮箱只能注册一次，就像现在大多数网站一样。所以我建议，注册页面为：邮箱，昵称，密码和重复密码

**Comment by tjwudi** [comment]
@Ada12 在#12中我们提到，密码输错可以通过邮箱找回。
