### ISSUE TITLE
未登录情况下，跳转到注册页，需要有介绍性内容

### ISSUE THREAD

**Issue by tjwudi** [Inter-U/prototype#6]
目前的设计是所有未登录的请求都跳转到登陆/注册页（login页），那么这个页面应该有我们站点的一些介绍、数据之类的东西。可以考虑设计一下，否则用户的跳失率可能很高。

可参考知乎，@29esther

![screen shot 2015-03-23 at 11 30 56 pm](https://cloud.githubusercontent.com/assets/5257816/6783439/b1a33536-d1b4-11e4-87db-43caa30b2db8.png)

**Comment by 29Esther** [comment]
OK~give me one night~ [wink..

**Comment by 29Esther** [comment]
已加

**Comment by tjwudi** [comment]
@29Esther 每次结束一个issue后，如果有对应改动代码的commit，就需要尽早push上来：）。commit message可以是像这样的

```
fixed #29
```

这样的话GitHub就会帮你自动关闭29号issue。

具体点说，假设别人给你提了一个issue，编号是29。编号在页面最上方可以看到，或者地址里面。

然后你改动了`index.html`，将这个issue修复了。于是你就commit：

```
$ git add index.html
$ git commit -m "fixed #29"
$ git push origin master
```

这样push上来之后，GitHub会自动帮你把29号issue关闭，并且在这个issue里面显示这个commit。

**Comment by 29Esther** [comment]
这样啊。。。
fixed #6

**Comment by tjwudi** [comment]
在这里说没有用滴。

**Comment by 29Esther** [comment]
问一下，我做Sprint 1 Spec Review。。
是一个Item提一个issue，还是在一个issue里面写完我对三个的意见啊？

**Comment by tjwudi** [comment]
as u wish @29Esther
