### ISSUE TITLE
注册/登录页面

### ISSUE THREAD

**Issue by Ada12** [Inter-U/prototype#8]
登录和注册页面应该是分开的吧
注册页面的提交按钮下方应该添加一句：已有账号？请登录
登录页面的提交按钮下方应该添加一句：还没有账号？请注册

**Comment by 29Esther** [comment]
不分开。减少页面数量。
所以，可登陆可注册。。

**Comment by Ada12** [comment]
我还是觉得应该分开比较好，如果不分开的话至少不能同时出现，可以加一个tab切换一下

**Comment by tjwudi** [comment]
现在这样设计确实有点挤，我的建议也是tab。  @29Esther
