### ISSUE TITLE
企业链接

### ISSUE THREAD

**Issue by Ada12** [Inter-U/prototype#9]
看不太懂这个页面为什么会需要这么多企业链接？是做推广吗？

**Comment by 29Esther** [comment]
嗯。是做推广，解决企业需求的。。
>#企业：
>- 发布最近招聘的职位（侧边栏组件）
>- 设立相册放办公室照片（侧边栏组件）

**Comment by tjwudi** [comment]
这个地方还需要明确一下究竟是什么类型的链接，是做什么的。不一定是只有文字，链接也可能在左边有图片之类的。

**Comment by tjwudi** [comment]
Closing this out of further discussion
